-- Drive Mapping MVS schema for Supabase
-- Run this file in the Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  avatar_path text,
  bio text check (bio is null or char_length(bio) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists avatar_path text;

alter table public.profiles
  add column if not exists bio text check (bio is null or char_length(bio) <= 1000);

create table if not exists public.routes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) <= 100),
  summary text check (summary is null or char_length(summary) <= 255),
  description text,
  address text check (address is null or char_length(address) <= 255),
  site_url text,
  prefecture_code int not null check (prefecture_code between 1 and 47),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.route_prefectures (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  prefecture_code int not null check (prefecture_code between 1 and 47),
  is_main boolean not null default false,
  unique (route_id, prefecture_code)
);

create table if not exists public.route_points (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  point_type text not null check (point_type in ('start', 'middle', 'goal')),
  label text,
  address text,
  sort_order int not null default 0
);

create table if not exists public.route_photos (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  storage_path text not null,
  thumb_path text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.route_likes (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (route_id, user_id)
);

create table if not exists public.profile_follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references auth.users(id) on delete cascade,
  followee_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, followee_id),
  check (follower_id <> followee_id)
);

create index if not exists routes_user_id_idx on public.routes(user_id);
create index if not exists routes_prefecture_code_idx on public.routes(prefecture_code);
create index if not exists route_prefectures_route_id_idx on public.route_prefectures(route_id);
create index if not exists route_prefectures_prefecture_code_idx on public.route_prefectures(prefecture_code);
create index if not exists route_points_route_id_idx on public.route_points(route_id);
create index if not exists route_photos_route_id_idx on public.route_photos(route_id);
create index if not exists route_likes_route_id_idx on public.route_likes(route_id);
create index if not exists route_likes_user_id_idx on public.route_likes(user_id);
create index if not exists profile_follows_follower_id_idx on public.profile_follows(follower_id);
create index if not exists profile_follows_followee_id_idx on public.profile_follows(followee_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_routes_updated_at on public.routes;
create trigger set_routes_updated_at
before update on public.routes
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('route-photos', 'route-photos', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('profile-icons', 'profile-icons', true)
on conflict (id) do update set public = excluded.public;

alter table public.profiles enable row level security;
alter table public.routes enable row level security;
alter table public.route_prefectures enable row level security;
alter table public.route_points enable row level security;
alter table public.route_photos enable row level security;
alter table public.route_likes enable row level security;
alter table public.profile_follows enable row level security;

drop policy if exists "Profiles are readable by everyone" on public.profiles;
create policy "Profiles are readable by everyone"
on public.profiles for select
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
with check (id = auth.uid());

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "Routes are readable by everyone" on public.routes;
create policy "Routes are readable by everyone"
on public.routes for select
using (true);

drop policy if exists "Authenticated users can create routes" on public.routes;
create policy "Authenticated users can create routes"
on public.routes for insert
with check (auth.role() = 'authenticated' and user_id = auth.uid());

drop policy if exists "Owners can update routes" on public.routes;
create policy "Owners can update routes"
on public.routes for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Owners can delete routes" on public.routes;
create policy "Owners can delete routes"
on public.routes for delete
using (user_id = auth.uid());

drop policy if exists "Route prefectures are readable by everyone" on public.route_prefectures;
create policy "Route prefectures are readable by everyone"
on public.route_prefectures for select
using (true);

drop policy if exists "Route owners can insert prefectures" on public.route_prefectures;
create policy "Route owners can insert prefectures"
on public.route_prefectures for insert
with check (
  exists (
    select 1 from public.routes
    where routes.id = route_prefectures.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route owners can update prefectures" on public.route_prefectures;
create policy "Route owners can update prefectures"
on public.route_prefectures for update
using (
  exists (
    select 1 from public.routes
    where routes.id = route_prefectures.route_id
      and routes.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.routes
    where routes.id = route_prefectures.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route owners can delete prefectures" on public.route_prefectures;
create policy "Route owners can delete prefectures"
on public.route_prefectures for delete
using (
  exists (
    select 1 from public.routes
    where routes.id = route_prefectures.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route points are readable by everyone" on public.route_points;
create policy "Route points are readable by everyone"
on public.route_points for select
using (true);

drop policy if exists "Route owners can insert points" on public.route_points;
create policy "Route owners can insert points"
on public.route_points for insert
with check (
  exists (
    select 1 from public.routes
    where routes.id = route_points.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route owners can update points" on public.route_points;
create policy "Route owners can update points"
on public.route_points for update
using (
  exists (
    select 1 from public.routes
    where routes.id = route_points.route_id
      and routes.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.routes
    where routes.id = route_points.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route owners can delete points" on public.route_points;
create policy "Route owners can delete points"
on public.route_points for delete
using (
  exists (
    select 1 from public.routes
    where routes.id = route_points.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route photos are readable by everyone" on public.route_photos;
create policy "Route photos are readable by everyone"
on public.route_photos for select
using (true);

drop policy if exists "Route owners can insert photos" on public.route_photos;
create policy "Route owners can insert photos"
on public.route_photos for insert
with check (
  exists (
    select 1 from public.routes
    where routes.id = route_photos.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route owners can delete photos" on public.route_photos;
create policy "Route owners can delete photos"
on public.route_photos for delete
using (
  exists (
    select 1 from public.routes
    where routes.id = route_photos.route_id
      and routes.user_id = auth.uid()
  )
);

drop policy if exists "Route likes are readable by everyone" on public.route_likes;
create policy "Route likes are readable by everyone"
on public.route_likes for select
using (true);

drop policy if exists "Authenticated users can like routes" on public.route_likes;
create policy "Authenticated users can like routes"
on public.route_likes for insert
with check (auth.role() = 'authenticated' and user_id = auth.uid());

drop policy if exists "Users can remove their own likes" on public.route_likes;
create policy "Users can remove their own likes"
on public.route_likes for delete
using (user_id = auth.uid());

drop policy if exists "Follows are readable by everyone" on public.profile_follows;
create policy "Follows are readable by everyone"
on public.profile_follows for select
using (true);

drop policy if exists "Authenticated users can follow profiles" on public.profile_follows;
create policy "Authenticated users can follow profiles"
on public.profile_follows for insert
with check (auth.role() = 'authenticated' and follower_id = auth.uid());

drop policy if exists "Users can remove their own follows" on public.profile_follows;
create policy "Users can remove their own follows"
on public.profile_follows for delete
using (follower_id = auth.uid());

drop policy if exists "Route photos are publicly readable" on storage.objects;
create policy "Route photos are publicly readable"
on storage.objects for select
using (bucket_id = 'route-photos');

drop policy if exists "Authenticated users can upload route photos" on storage.objects;
create policy "Authenticated users can upload route photos"
on storage.objects for insert
with check (bucket_id = 'route-photos' and auth.role() = 'authenticated');

drop policy if exists "Users can delete their own route photos" on storage.objects;
create policy "Users can delete their own route photos"
on storage.objects for delete
using (bucket_id = 'route-photos' and owner = auth.uid());

drop policy if exists "Profile icons are publicly readable" on storage.objects;
create policy "Profile icons are publicly readable"
on storage.objects for select
using (bucket_id = 'profile-icons');

drop policy if exists "Authenticated users can upload profile icons" on storage.objects;
create policy "Authenticated users can upload profile icons"
on storage.objects for insert
with check (bucket_id = 'profile-icons' and auth.role() = 'authenticated');

drop policy if exists "Users can update their own profile icons" on storage.objects;
create policy "Users can update their own profile icons"
on storage.objects for update
using (bucket_id = 'profile-icons' and owner = auth.uid())
with check (bucket_id = 'profile-icons' and owner = auth.uid());

drop policy if exists "Users can delete their own profile icons" on storage.objects;
create policy "Users can delete their own profile icons"
on storage.objects for delete
using (bucket_id = 'profile-icons' and owner = auth.uid());

